# Generated by Django 5.0.6 on 2024-07-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100)),
                ('quarter_no', models.CharField(max_length=100)),
                ('previous_reading', models.PositiveIntegerField(default=0)),
                ('current_reading', models.PositiveIntegerField()),
                ('electricity_units', models.PositiveIntegerField()),
                ('meter_image', models.ImageField(upload_to='meter_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
