# Generated by Django 5.0.6 on 2024-07-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_meterreading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreading',
            name='previous_reading',
        ),
        migrations.AddField(
            model_name='meterreading',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('incorrect_image', 'Meter image not correct'), ('unclear_reading', 'Image reading not clear'), ('different_meter', 'Different meter'), ('wrong_reading', 'Inserting wrong reading')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='current_reading',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='electricity_units',
            field=models.IntegerField(),
        ),
    ]
